//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace APKInstaller.Strings.InstallPage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InstallStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstallStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APKInstaller.Strings.InstallPage.InstallStrings", typeof(InstallStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ADB, the Android Debug Bridge, is needed for APK Installer to work. Click &quot;Download&quot; to download it. By downloading, you accept the Google Terms and Conditions for ADB. If you have already downloaded ADB, click &quot;Select&quot; to select it. 的本地化字符串。
        /// </summary>
        public static string AboutADB {
            get {
                return ResourceManager.GetString("AboutADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ADB Exist 的本地化字符串。
        /// </summary>
        public static string ADBExist {
            get {
                return ResourceManager.GetString("ADBExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ADB is missing 的本地化字符串。
        /// </summary>
        public static string ADBMissing {
            get {
                return ResourceManager.GetString("ADBMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capabilities: 的本地化字符串。
        /// </summary>
        public static string AppCapabilities_HeadText {
            get {
                return ResourceManager.GetString("AppCapabilities.HeadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot open app package 的本地化字符串。
        /// </summary>
        public static string CannotOpenPackage {
            get {
                return ResourceManager.GetString("CannotOpenPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking... 的本地化字符串。
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking ADB... 的本地化字符串。
        /// </summary>
        public static string CheckingADB {
            get {
                return ResourceManager.GetString("CheckingADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose ADB 的本地化字符串。
        /// </summary>
        public static string ChooseADB {
            get {
                return ResourceManager.GetString("ChooseADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to read them 的本地化字符串。
        /// </summary>
        public static string ClickToRead {
            get {
                return ResourceManager.GetString("ClickToRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Devices 的本地化字符串。
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Failed 的本地化字符串。
        /// </summary>
        public static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please check your network connection or the URL and try again. 的本地化字符串。
        /// </summary>
        public static string DownloadFailedInfo {
            get {
                return ResourceManager.GetString("DownloadFailedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finding WSA... 的本地化字符串。
        /// </summary>
        public static string FindingWSA {
            get {
                return ResourceManager.GetString("FindingWSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished 的本地化字符串。
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WSA Found 的本地化字符串。
        /// </summary>
        public static string FoundWSA {
            get {
                return ResourceManager.GetString("FoundWSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to Setting 的本地化字符串。
        /// </summary>
        public static string GoToSetting {
            get {
                return ResourceManager.GetString("GoToSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How to connect WSA? 的本地化字符串。
        /// </summary>
        public static string HowToConnect {
            get {
                return ResourceManager.GetString("HowToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. Please make sure APK Installer has been updated to the latest version
        ///2. Make sure you have the Android Subsystem installed and running
        ///3. Turn on developer mode and make sure the IP address is displayed successfully
        ///4. Reopen APK Installer and continue your installation 的本地化字符串。
        /// </summary>
        public static string HowToConnectInfo {
            get {
                return ResourceManager.GetString("HowToConnectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I Know 的本地化字符串。
        /// </summary>
        public static string IKnow {
            get {
                return ResourceManager.GetString("IKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is ready! 的本地化字符串。
        /// </summary>
        public static string InstalledFormat {
            get {
                return ResourceManager.GetString("InstalledFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install {0}? 的本地化字符串。
        /// </summary>
        public static string InstallFormat {
            get {
                return ResourceManager.GetString("InstallFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installing... 的本地化字符串。
        /// </summary>
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reason: 的本地化字符串。
        /// </summary>
        public static string InstallOutputTextBlock_Text {
            get {
                return ResourceManager.GetString("InstallOutputTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The package is either corrupted or invalid. 的本地化字符串。
        /// </summary>
        public static string InvalidPackage {
            get {
                return ResourceManager.GetString("InvalidPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The URL is either Incomplete or invalid. 的本地化字符串。
        /// </summary>
        public static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch 的本地化字符串。
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launching WSA... 的本地化字符串。
        /// </summary>
        public static string LaunchingWSA {
            get {
                return ResourceManager.GetString("LaunchingWSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch when ready 的本地化字符串。
        /// </summary>
        public static string LaunchWhenReadyCheckbox_Content {
            get {
                return ResourceManager.GetString("LaunchWhenReadyCheckbox.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find Android Device 的本地化字符串。
        /// </summary>
        public static string NoDevice {
            get {
                return ResourceManager.GetString("NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can install WSA. Or go to Settings to connect Device. 的本地化字符串。
        /// </summary>
        public static string NoDeviceInfo {
            get {
                return ResourceManager.GetString("NoDeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can go to Settings to connect Device. 的本地化字符串。
        /// </summary>
        public static string NoDeviceInfo10 {
            get {
                return ResourceManager.GetString("NoDeviceInfo10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot connect Internet 的本地化字符串。
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please connect to the internet before opening the app. 的本地化字符串。
        /// </summary>
        public static string NoInternetInfo {
            get {
                return ResourceManager.GetString("NoInternetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For proper functioning of the app, try to launch an Android app package. 的本地化字符串。
        /// </summary>
        public static string NoPackageWranning {
            get {
                return ResourceManager.GetString("NoPackageWranning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online Package 的本地化字符串。
        /// </summary>
        public static string OnlinePackage {
            get {
                return ResourceManager.GetString("OnlinePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open APK File 的本地化字符串。
        /// </summary>
        public static string OpenAPK {
            get {
                return ResourceManager.GetString("OpenAPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package Name: {0} 的本地化字符串。
        /// </summary>
        public static string PackageNameFormat {
            get {
                return ResourceManager.GetString("PackageNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reinstall 的本地化字符串。
        /// </summary>
        public static string Reinstall {
            get {
                return ResourceManager.GetString("Reinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is already installed 的本地化字符串。
        /// </summary>
        public static string ReinstallFormat {
            get {
                return ResourceManager.GetString("ReinstallFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A newer version of {0} is already installed. 的本地化字符串。
        /// </summary>
        public static string ReinstallOutput {
            get {
                return ResourceManager.GetString("ReinstallOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retry 的本地化字符串。
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting ADB Server... 的本地化字符串。
        /// </summary>
        public static string StartingADB {
            get {
                return ResourceManager.GetString("StartingADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start WSA 的本地化字符串。
        /// </summary>
        public static string StartWSA {
            get {
                return ResourceManager.GetString("StartWSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unzip ADB... 的本地化字符串。
        /// </summary>
        public static string UnzipADB {
            get {
                return ResourceManager.GetString("UnzipADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unzip completed 的本地化字符串。
        /// </summary>
        public static string UnzipComplete {
            get {
                return ResourceManager.GetString("UnzipComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unzipping {0}/{1} ... 的本地化字符串。
        /// </summary>
        public static string UnzippingFormat {
            get {
                return ResourceManager.GetString("UnzippingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update {0}? 的本地化字符串。
        /// </summary>
        public static string UpdateFormat {
            get {
                return ResourceManager.GetString("UpdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: {0} 的本地化字符串。
        /// </summary>
        public static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait for download... 的本地化字符串。
        /// </summary>
        public static string WaitDownload {
            get {
                return ResourceManager.GetString("WaitDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for Device... 的本地化字符串。
        /// </summary>
        public static string WaitingDevice {
            get {
                return ResourceManager.GetString("WaitingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for install {0} 的本地化字符串。
        /// </summary>
        public static string WaitingForInstallFormat {
            get {
                return ResourceManager.GetString("WaitingForInstallFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting WSA Start...
        ///This may takes long time. Sit back and relax. 的本地化字符串。
        /// </summary>
        public static string WaitingWSAStart {
            get {
                return ResourceManager.GetString("WaitingWSAStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WSA is Running 的本地化字符串。
        /// </summary>
        public static string WSARunning {
            get {
                return ResourceManager.GetString("WSARunning", resourceCulture);
            }
        }
    }
}
