//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace APKInstaller.Strings.TestPage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APKInstaller.Strings.TestPage.TestStrings", typeof(TestStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Android Test 的本地化字符串。
        /// </summary>
        public static string AndroidTestSettingsHeader_Header {
            get {
                return ResourceManager.GetString("AndroidTestSettingsHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applications 的本地化字符串。
        /// </summary>
        public static string ApplicationsSettings_Header {
            get {
                return ResourceManager.GetString("ApplicationsSettings.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Backdrop Type for Windows 11 的本地化字符串。
        /// </summary>
        public static string BackdropSettings_Description {
            get {
                return ResourceManager.GetString("BackdropSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backdrop 的本地化字符串。
        /// </summary>
        public static string BackdropSettings_Header {
            get {
                return ResourceManager.GetString("BackdropSettings.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select language and restart to change language 的本地化字符串。
        /// </summary>
        public static string LanguageSettings_Description {
            get {
                return ResourceManager.GetString("LanguageSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string LanguageSettings_Header {
            get {
                return ResourceManager.GetString("LanguageSettings.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processes 的本地化字符串。
        /// </summary>
        public static string ProcessesSettings_Header {
            get {
                return ResourceManager.GetString("ProcessesSettings.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Progress Ring on the Title Bar 的本地化字符串。
        /// </summary>
        public static string ProgressSettings_Description {
            get {
                return ResourceManager.GetString("ProgressSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress 的本地化字符串。
        /// </summary>
        public static string ProgressSettings_Header {
            get {
                return ResourceManager.GetString("ProgressSettings.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string RadioThemeDark_Content {
            get {
                return ResourceManager.GetString("RadioThemeDark.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Default 的本地化字符串。
        /// </summary>
        public static string RadioThemeDefault_Content {
            get {
                return ResourceManager.GetString("RadioThemeDefault.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string RadioThemeLight_Content {
            get {
                return ResourceManager.GetString("RadioThemeLight.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Resize Mode of Window 的本地化字符串。
        /// </summary>
        public static string ResizeModeSettings_Description {
            get {
                return ResourceManager.GetString("ResizeModeSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resize Mode 的本地化字符串。
        /// </summary>
        public static string ResizeModeSettings_Header {
            get {
                return ResourceManager.GetString("ResizeModeSettings.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the value of Progress Ring 的本地化字符串。
        /// </summary>
        public static string SetProgressValue_Description {
            get {
                return ResourceManager.GetString("SetProgressValue.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress Value 的本地化字符串。
        /// </summary>
        public static string SetProgressValue_Header {
            get {
                return ResourceManager.GetString("SetProgressValue.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Refresh Button on the Title Bar 的本地化字符串。
        /// </summary>
        public static string ShowRefreshButton_Description {
            get {
                return ResourceManager.GetString("ShowRefreshButton.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Button 的本地化字符串。
        /// </summary>
        public static string ShowRefreshButton_Header {
            get {
                return ResourceManager.GetString("ShowRefreshButton.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App Theme 的本地化字符串。
        /// </summary>
        public static string ThemeSettings_Header {
            get {
                return ResourceManager.GetString("ThemeSettings.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Testing 的本地化字符串。
        /// </summary>
        public static string TitleBar_Title {
            get {
                return ResourceManager.GetString("TitleBar.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extends Content Into TitleBar 的本地化字符串。
        /// </summary>
        public static string TitleBarSettings_Description {
            get {
                return ResourceManager.GetString("TitleBarSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title Bar 的本地化字符串。
        /// </summary>
        public static string TitleBarSettings_Header {
            get {
                return ResourceManager.GetString("TitleBarSettings.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI Test 的本地化字符串。
        /// </summary>
        public static string UITestSettingsHeader_Header {
            get {
                return ResourceManager.GetString("UITestSettingsHeader.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Color Settings 的本地化字符串。
        /// </summary>
        public static string WindowsColorButton_Content {
            get {
                return ResourceManager.GetString("WindowsColorButton.Content", resourceCulture);
            }
        }
    }
}
